# Generated by Django 6.1.1 on 2026-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='photo_placeholder',
            field=models.CharField(blank=True, default='images/face_1.avif', help_text='Static path, e.g. images/counsellors/cards/thara.webp. Usually set automatically when you use Upload portrait in admin.', max_length=200),
        ),
    ]
