"""
Django settings for ProjectCounsellingSite project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY environment variable is not set")

# SECURITY WARNING: don't run with debug turned on in production!
# Render sets RENDER=true; default DEBUG off there, on locally. Explicit DEBUG wins.
_on_render = bool(os.environ.get("RENDER"))
if "DEBUG" in os.environ:
    DEBUG = os.environ["DEBUG"].lower() in ("true", "1", "yes")
else:
    DEBUG = not _on_render


ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]
if _on_render:
    ALLOWED_HOSTS.append(".onrender.com")

CSRF_TRUSTED_ORIGINS = ["https://*.onrender.com"]
for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(","):
    origin = origin.strip()
    if origin and origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProjectCounsellingSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProjectCounsellingSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Render Postgres (and any other host) injects DATABASE_URL; local stays SQLite.

if os.environ.get("DATABASE_URL"):
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Trust the reverse proxy's HTTPS hint; force secure cookies/HSTS off localhost.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600

# Tracebacks for 500s go to the process log (Render: service → Logs).
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Compress CSS/JS for WhiteNoise, but do not content-hash filenames.
# Manifest hashing produced URLs like index.dd4b7014a488.css while STATIC_ROOT
# only had index.css, so every stylesheet/image 404'd in production.
_static_backend = (
    "whitenoise.storage.CompressedStaticFilesStorage"
    if (_on_render or not DEBUG)
    else "django.contrib.staticfiles.storage.StaticFilesStorage"
)

# Optional leftover local-disk uploads. Counsellor portraits now live under
# static/images/counsellors/ and are served as static files. When
# AWS_STORAGE_BUCKET_NAME is set, any remaining FileField uploads go to S3/R2.
MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
if not MEDIA_URL.startswith(("http://", "https://")):
    if not MEDIA_URL.startswith("/"):
        MEDIA_URL = f"/{MEDIA_URL}"
    if not MEDIA_URL.endswith("/"):
        MEDIA_URL += "/"
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": _static_backend,
    },
}

_aws_bucket = os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
if _aws_bucket:
    _aws_domain = os.environ.get("AWS_S3_CUSTOM_DOMAIN", "")
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": os.environ.get("AWS_ACCESS_KEY_ID", ""),
            "secret_key": os.environ.get("AWS_SECRET_ACCESS_KEY", ""),
            "bucket_name": _aws_bucket,
            "region_name": os.environ.get("AWS_S3_REGION_NAME", "auto"),
            "endpoint_url": os.environ.get("AWS_S3_ENDPOINT_URL") or None,
            "custom_domain": _aws_domain or None,
            "default_acl": None,
            "querystring_auth": False,
            "file_overwrite": True,
            "object_parameters": {
                "CacheControl": "public, max-age=31536000, immutable",
            },
        },
    }
    if _aws_domain:
        MEDIA_URL = f"https://{_aws_domain}/"
    elif os.environ.get("MEDIA_URL"):
        MEDIA_URL = os.environ["MEDIA_URL"]
    else:
        MEDIA_URL = f"https://{_aws_bucket}.s3.amazonaws.com/"


# Email — console backend locally. When EMAIL_HOST is set, use SMTP.
_email_host = os.environ.get("EMAIL_HOST", "")
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.smtp.EmailBackend"
        if _email_host
        else "django.core.mail.backends.console.EmailBackend"
    ),
)
EMAIL_HOST = _email_host
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("true", "1", "yes")
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Shared Counselling <sharedcounselling@gmail.com>",
)
BOOKING_NOTIFY_EMAIL = os.environ.get(
    "BOOKING_NOTIFY_EMAIL",
    "sharedcounselling@gmail.com",
)